<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.8" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EonVientiane.CLI\EonVientiane.CLI.csproj" />
    <ProjectReference Include="..\EonVientiane.Core\EonVientiane.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\Silver.ttf" Link="Assets\Fonts\Silver.ttf" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

</Project>